(() => {
  const Core=window.SurwaveEditorCoreV2;
  const $=id=>document.getElementById(id);
  const refs={pageList:$('pageList'),pageSearch:$('pageSearch'),title:$('pageTitle'),group:$('pageGroup'),path:$('pagePath'),blocks:$('blocks'),preview:$('preview'),saveState:$('saveState'),toast:$('toast'),picker:$('mediaPicker'),workspace:document.querySelector('.workspace'),previewPanel:$('previewPanel')};
  const state={pages:[],groups:[],path:'',originalPath:'',title:'',group:'',frontmatter:'',blocks:[],dirty:false,currentHref:'',newMode:false,pathTouched:false};
  let previewTimer,toastTimer,pendingUpload=null,dragging=null;

  function toast(text){refs.toast.textContent=text;refs.toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>refs.toast.classList.remove('visible'),2000)}
  function status(text,kind=''){refs.saveState.textContent=text;refs.saveState.className='save-state '+kind}
  function dirty(){state.dirty=true;status('Есть изменения','dirty');schedulePreview()}
  async function api(url,options={}){const r=await fetch(url,{cache:'no-store',...options});let d={};try{d=await r.json()}catch(_){d={error:`HTTP ${r.status}`}}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
  const sourceToHref=p=>(/(^|\/)README\.md$/i.test(p)?p.replace(/README\.md$/i,'index.html'):p.replace(/\.md$/i,'.html'));
  const pageByPath=p=>state.pages.find(x=>x.path===p);
  function normalizePath(v){let p=String(v||'').trim().replace(/\\/g,'/').replace(/^\/+|\/+$/g,'').replace(/\s+/g,'-');if(p&&!/\.md$/i.test(p))p+='.md';return p}

  async function refreshPages(render=true){const d=await api('/api/editor/pages');state.pages=d.pages||[];state.groups=d.groups||[];fillGroups(state.group||state.groups[0]||'Главная');if(render)renderPageList()}
  function fillGroups(selected){const values=[...new Set([...state.groups,selected].filter(Boolean))];refs.group.innerHTML=values.map(g=>`<option value="${Core.esc(g)}">${Core.esc(g)}</option>`).join('')+'<option value="__new__">+ Новый раздел…</option>';refs.group.value=values.includes(selected)?selected:(values[0]||'')}
  function renderPageList(){const q=refs.pageSearch.value.trim().toLowerCase();refs.pageList.innerHTML='';const groups=new Map();for(const p of state.pages){if(q&&!`${p.title} ${p.path}`.toLowerCase().includes(q))continue;const g=p.group||'Без раздела';if(!groups.has(g))groups.set(g,[]);groups.get(g).push(p)}for(const [g,pages] of groups){const h=document.createElement('div');h.className='page-group-title';h.textContent=g;refs.pageList.appendChild(h);for(const p of pages){const b=document.createElement('button');b.className='page-item'+(p.path===state.originalPath?' active':'');b.innerHTML=`${Core.esc(p.title)}<small>${Core.esc(p.path)}</small>`;b.onclick=()=>loadPage(p.path);refs.pageList.appendChild(b)}}}
  function canLeave(){return !state.dirty||confirm('Есть несохранённые изменения. Продолжить без сохранения?')}
  async function loadPage(path){if(path===state.originalPath&&!state.newMode)return;if(!canLeave())return;try{status('Открываю…');const d=await api('/api/editor/page?path='+encodeURIComponent(path));await refreshPages(false);const meta=pageByPath(path)||{};const doc=Core.parseDocument(d.content||'');state.path=path;state.originalPath=path;state.title=meta.title||Core.stripHtml(doc.blocks.find(x=>x.type==='heading'&&x.level===1)?.html||'Без названия');state.group=meta.group||state.groups[0]||'Главная';state.frontmatter=doc.frontmatter;state.blocks=doc.blocks;state.currentHref='/surwave-site/wiki/'+(meta.href||sourceToHref(path));state.dirty=false;state.newMode=false;state.pathTouched=false;syncMeta();renderAll();renderPageList();status('Загружено','saved')}catch(e){toast('Ошибка: '+e.message);status('Ошибка')}}
  function syncMeta(){refs.title.value=state.title;refs.path.value=state.path;fillGroups(state.group)}
  function newPage(){if(!canLeave())return;state.path='pages/novaya-stranica.md';state.originalPath='';state.title='Новая страница';state.group=state.groups[0]||'Главная';state.frontmatter='';state.blocks=[{type:'heading',level:1,html:'Новая страница',align:'left'},{type:'text',html:'Начните писать содержимое страницы…',align:'left'}];state.dirty=true;state.currentHref='';state.newMode=true;state.pathTouched=false;syncMeta();renderAll();renderPageList();status('Новая страница','dirty')}
  function duplicate(){state.originalPath='';state.path=state.path.replace(/\.md$/i,'-copy.md');state.title+=' — копия';state.blocks=Core.clone(state.blocks);state.dirty=true;state.newMode=true;state.pathTouched=true;syncMeta();renderAll();status('Копия — не сохранена','dirty')}

  function btn(text,title,fn,extra=''){const b=document.createElement('button');b.type='button';b.className='icon-btn '+extra;b.textContent=text;b.title=title;b.onclick=e=>{e.stopPropagation();fn()};return b}
  function input(value,fn,placeholder='',cls=''){const x=document.createElement('input');x.className='field '+cls;x.value=value??'';x.placeholder=placeholder;x.oninput=()=>{fn(x.value);dirty()};return x}
  function area(value,fn,cls=''){const x=document.createElement('textarea');x.className='field textarea '+cls;x.value=value??'';x.oninput=()=>{fn(x.value);dirty()};return x}
  function select(options,value,fn,cls=''){const s=document.createElement('select');s.className='field '+cls;for(const [v,l] of options){const o=document.createElement('option');o.value=v;o.textContent=l;s.appendChild(o)}s.value=String(value??'');s.onchange=()=>{fn(s.value);dirty()};return s}
  function colorControl(value,fn,label='Цвет'){const w=document.createElement('label');w.className='color-control';w.append(document.createTextNode(label));const c=document.createElement('input');c.type='color';c.value=/^#[0-9a-f]{6}$/i.test(value||'')?value:'#00ff78';const t=input(value||'',v=>fn(v),'#00ff78','color-text');c.oninput=()=>{t.value=c.value;fn(c.value);dirty()};w.append(c,t);return w}

  function applyStyle(editor,prop,value){editor.focus();const sel=window.getSelection();if(!sel.rangeCount)return;const range=sel.getRangeAt(0);if(!editor.contains(range.commonAncestorContainer))return;const span=document.createElement('span');span.style.setProperty(prop,value);try{range.surroundContents(span)}catch(_){document.execCommand('insertHTML',false,`<span style="${prop}:${Core.esc(value)}">${Core.esc(sel.toString())}</span>`)} }
  function rich(block,key='html'){
    const wrap=document.createElement('div'),bar=document.createElement('div'),ed=document.createElement('div');bar.className='rich-toolbar';ed.className='rich-editor';ed.contentEditable='true';ed.innerHTML=block[key]||'';
    const command=(label,title,cmd)=>{const b=document.createElement('button');b.type='button';b.innerHTML=label;b.title=title;b.onmousedown=e=>{e.preventDefault();cmd();block[key]=ed.innerHTML;dirty()};bar.appendChild(b)};
    command('<b>B</b>','Жирный',()=>document.execCommand('bold'));command('<i>I</i>','Курсив',()=>document.execCommand('italic'));command('<u>U</u>','Подчёркивание',()=>document.execCommand('underline'));command('<s>S</s>','Зачёркивание',()=>document.execCommand('strikeThrough'));command('&lt;/&gt;','Код',()=>document.execCommand('formatBlock',false,'code'));
    const textColor=document.createElement('input');textColor.type='color';textColor.value='#00ff78';textColor.title='Цвет текста';textColor.oninput=()=>{applyStyle(ed,'color',textColor.value);block[key]=ed.innerHTML;dirty()};bar.appendChild(textColor);
    const highlight=document.createElement('input');highlight.type='color';highlight.value='#ffe066';highlight.title='Цвет выделения';highlight.oninput=()=>{applyStyle(ed,'background-color',highlight.value);block[key]=ed.innerHTML;dirty()};bar.appendChild(highlight);
    const size=select([['13px','Мелкий'],['15px','Обычный'],['18px','Крупный'],['22px','Очень крупный']], '15px',v=>{applyStyle(ed,'font-size',v);block[key]=ed.innerHTML},'rich-size');bar.appendChild(size);
    command('🔗','Гиперссылка',()=>{const u=prompt('Ссылка:','https://');if(u)document.execCommand('createLink',false,u)});
    ed.oninput=()=>{block[key]=ed.innerHTML;dirty()};wrap.append(bar,ed);return wrap;
  }

  function addBar(host,array){host.innerHTML='';const w=document.createElement('div');w.className='add-bar';const s=select(Core.TYPES.filter(([t])=>t!=='raw'),'text',()=>{},'small-select');const b=document.createElement('button');b.className='btn';b.textContent='+ Добавить блок';b.onclick=()=>{array.push(Core.defaultBlock(s.value));dirty();renderAll()};w.append(s,b);host.appendChild(w)}
  function move(arr,i,d){const j=i+d;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];dirty();renderAll()}
  function renderBlocks(container,array,base=''){
    container.innerHTML='';
    array.forEach((block,i)=>{const path=base?`${base}.${i}`:`${i}`;const card=document.createElement('section');card.className='block-card';card.dataset.editorPath=path;card.draggable=true;
      const head=document.createElement('div');head.className='block-head';const drag=document.createElement('span');drag.className='drag-handle';drag.textContent='⠿';const kind=document.createElement('span');kind.className='block-kind';kind.textContent=Core.TYPES.find(([t])=>t===block.type)?.[1]||block.type;const spacer=document.createElement('span');spacer.className='block-spacer';head.append(drag,kind,spacer,btn('↑','Выше',()=>move(array,i,-1)),btn('↓','Ниже',()=>move(array,i,1)),btn('⧉','Дублировать',()=>{array.splice(i+1,0,Core.clone(block));dirty();renderAll()}),btn('×','Удалить',()=>{array.splice(i,1);dirty();renderAll()},'remove'));card.appendChild(head);
      const body=document.createElement('div');body.className='block-body';renderBlock(body,block,path);card.appendChild(body);
      card.addEventListener('dragstart',()=>dragging={array,index:i});card.addEventListener('dragover',e=>{if(dragging?.array===array)e.preventDefault()});card.addEventListener('drop',e=>{if(dragging?.array!==array)return;e.preventDefault();const item=array.splice(dragging.index,1)[0];let target=i;if(dragging.index<i)target--;array.splice(target,0,item);dragging=null;dirty();renderAll()});
      card.onclick=e=>{if(e.target.closest('button,input,textarea,select,.rich-editor'))return;highlightPreview(path)};container.appendChild(card);
    });
  }
  function nested(parent,title,children,base){const z=document.createElement('div');z.className='nested-zone';const h=document.createElement('div');h.className='nested-title';h.textContent=title;const add=document.createElement('button');add.className='btn';add.textContent='+ Блок';add.onclick=()=>{children.push(Core.defaultBlock('text'));dirty();renderAll()};h.appendChild(add);const list=document.createElement('div');list.className='blocks';z.append(h,list);renderBlocks(list,children,base);parent.appendChild(z)}

  function mediaButton(target,key,label='Загрузить изображение'){const b=document.createElement('button');b.className='btn';b.textContent=label;b.onclick=()=>{pendingUpload={target,key};refs.picker.value='';refs.picker.click()};return b}
  function renderBlock(body,b,path){
    if(b.type==='heading'){const row=document.createElement('div');row.className='control-row';row.append(select([[1,'H1'],[2,'H2'],[3,'H3'],[4,'H4'],[5,'H5'],[6,'H6']],b.level,v=>b.level=+v,'small-select'),select([['left','Слева'],['center','По центру'],['right','Справа']],b.align||'left',v=>b.align=v,'small-select'));body.append(row,rich(b));return}
    if(b.type==='text'){body.append(select([['left','Слева'],['center','По центру'],['right','Справа']],b.align||'left',v=>b.align=v,'small-select'),rich(b));return}
    if(b.type==='image'){body.append(input(b.src,v=>b.src=v,'.gitbook/assets/image.png'),input(b.caption,v=>b.caption=v,'Подпись'),mediaButton(b,'src'));return}
    if(b.type==='list'){const top=document.createElement('div');top.className='control-row';top.append(select([['false','Маркированный'],['true','Нумерованный']],String(!!b.ordered),v=>b.ordered=v==='true','small-select'));const add=document.createElement('button');add.className='btn';add.textContent='+ Пункт';add.onclick=()=>{b.items.push('Новый пункт');dirty();renderAll()};top.append(add);body.append(top);(b.items||[]).forEach((it,i)=>{const r=document.createElement('div');r.className='list-row';r.append(input(it,v=>b.items[i]=v,'Пункт'),btn('×','Удалить',()=>{b.items.splice(i,1);dirty();renderAll()},'remove'));body.append(r)});return}
    if(b.type==='quote'){body.append(rich(b));return}
    if(b.type==='hint'){const row=document.createElement('div');row.className='control-row';row.append(select([['info','Info'],['warning','Warning'],['success','Success'],['danger','Danger']],b.style||'info',v=>b.style=v,'small-select'),colorControl(b.color||'',v=>b.color=v,'Цвет рамки'));body.append(row);nested(body,'Содержимое hint',b.children||(b.children=[]),`${path}.children`);return}
    if(b.type==='details'){body.append(rich(b,'summaryHtml'));nested(body,'Содержимое раскрывающегося блока',b.children||(b.children=[]),`${path}.children`);return}
    if(b.type==='stepper'){(b.steps||(b.steps=[])).forEach((s,i)=>{const c=document.createElement('div');c.className='step-card';const h=document.createElement('div');h.className='step-head';h.append(document.createTextNode(`Шаг ${i+1}`),btn('↑','Выше',()=>{if(i){[b.steps[i-1],b.steps[i]]=[b.steps[i],b.steps[i-1]];dirty();renderAll()}}),btn('↓','Ниже',()=>{if(i<b.steps.length-1){[b.steps[i+1],b.steps[i]]=[b.steps[i],b.steps[i+1]];dirty();renderAll()}}),btn('×','Удалить',()=>{b.steps.splice(i,1);dirty();renderAll()},'remove'));c.append(h);nested(c,`Блоки шага ${i+1}`,s.children||(s.children=[]),`${path}.steps.${i}.children`);body.append(c)});const add=document.createElement('button');add.className='btn';add.textContent='+ Добавить шаг';add.onclick=()=>{b.steps.push({children:[Core.defaultBlock('text')]});dirty();renderAll()};body.append(add);return}
    if(b.type==='recipe'){body.append(document.createTextNode('Название напитка'),rich(b,'nameHtml'),document.createTextNode('Описание / параметры'),rich(b,'bodyHtml'));return}
    if(b.type==='mention'){const pick=select([['','Выбрать страницу Wiki…'],...state.pages.map(p=>[p.path,p.title])],'',v=>{if(v){b.url=v;b.label=pageByPath(v)?.title||b.label;dirty();renderAll()}},'');body.append(rich(b,'prefixHtml'),pick,input(b.label,v=>b.label=v,'Подпись ссылки'),input(b.url,v=>b.url=v,'Путь .md или URL'));return}
    if(b.type==='linkgroup'){(b.items||(b.items=[])).forEach((it,i)=>{const c=document.createElement('div');c.className='link-editor-item';c.append(input(it.title,v=>it.title=v,'Название'),input(it.url,v=>it.url=v,'Ссылка'),rich(it,'description'),input(it.image,v=>it.image=v,'Изображение (необязательно)'),mediaButton(it,'image'),btn('×','Удалить ссылку',()=>{b.items.splice(i,1);dirty();renderAll()},'remove'));body.append(c)});const add=document.createElement('button');add.className='btn';add.textContent='+ Добавить ссылку в блок';add.onclick=()=>{b.items.push({title:'Новая ссылка',url:'',description:'',image:''});dirty();renderAll()};body.append(add);return}
    if(b.type==='embed'){body.append(input(b.url,v=>b.url=v,'URL'),rich(b,'title'),rich(b,'description'),input(b.image,v=>b.image=v,'Изображение превью (необязательно)'),mediaButton(b,'image','Загрузить превью'));return}
    if(b.type==='table'){const table=document.createElement('table');table.className='table-grid';(b.rows||(b.rows=[['Заголовок']])).forEach((r,ri)=>{const tr=document.createElement('tr');r.forEach((c,ci)=>{const td=document.createElement('td');td.append(input(c,v=>b.rows[ri][ci]=v));tr.append(td)});table.append(tr)});body.append(table);const row=document.createElement('div');row.className='control-row';for(const [t,fn] of [['+ Строка',()=>b.rows.push(Array(Math.max(...b.rows.map(r=>r.length),1)).fill(''))],['+ Столбец',()=>b.rows.forEach(r=>r.push(''))],['− Строка',()=>{if(b.rows.length>1)b.rows.pop()}],['− Столбец',()=>{if(b.rows[0]?.length>1)b.rows.forEach(r=>r.pop())}]]){const x=document.createElement('button');x.className='btn';x.textContent=t;x.onclick=()=>{fn();dirty();renderAll()};row.append(x)}body.append(row);return}
    if(b.type==='code'){body.append(input(b.language,v=>b.language=v,'Язык'),area(b.code,v=>b.code=v,'codearea'));return}
    if(b.type==='divider'){body.textContent='Горизонтальный разделитель';return}
    if(b.type==='raw'){body.append(document.createTextNode('Фрагмент пока не распознан. Его можно сохранить как есть.'),area(b.markdown,v=>b.markdown=v,'codearea'));return}
  }

  function renderAll(){addBar($('mainAddBar'),state.blocks);addBar($('bottomAddBar'),state.blocks);renderBlocks(refs.blocks,state.blocks);schedulePreview()}
  function schedulePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(updatePreview,100)}
  function updatePreview(){const html=Core.renderBlocksHtml(state.blocks);refs.preview.srcdoc=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><base href="${location.origin}/"><style>${Core.previewCss}</style></head><body><article class="article">${html}</article></body></html>`;refs.preview.onload=bindPreviewClicks}
  function bindPreviewClicks(){const doc=refs.preview.contentDocument;if(!doc)return;doc.querySelectorAll('[data-editor-path]').forEach(el=>{el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();focusEditor(el.dataset.editorPath)});});}
  function focusEditor(path){document.querySelectorAll('.block-card.preview-focus').forEach(x=>x.classList.remove('preview-focus'));const card=document.querySelector(`.block-card[data-editor-path="${CSS.escape(path)}"]`);if(!card)return;card.classList.add('preview-focus');card.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>card.classList.remove('preview-focus'),1800)}
  function highlightPreview(path){const doc=refs.preview.contentDocument;if(!doc)return;doc.querySelectorAll('.preview-focus').forEach(x=>x.classList.remove('preview-focus'));const el=doc.querySelector(`[data-editor-path="${CSS.escape(path)}"]`);if(el){el.classList.add('preview-focus');el.scrollIntoView({behavior:'smooth',block:'center'})}}

  function currentContent(){return Core.serializeDocument(state.frontmatter,state.blocks)}
  async function save(){state.title=refs.title.value.trim()||'Без названия';state.group=refs.group.value||'Разделы';state.path=normalizePath(refs.path.value);refs.path.value=state.path;if(!state.path)return toast('Укажи файл страницы');try{status('Сохраняю…');const old=state.originalPath;const d=await api('/api/editor/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:state.path,title:state.title,group:state.group,content:currentContent()})});if(old&&old!==state.path)await api('/api/editor/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:old})});state.originalPath=state.path;state.currentHref=d.href;state.dirty=false;state.newMode=false;await refreshPages();status('Сохранено','saved');toast('Страница сохранена')}catch(e){status('Ошибка');toast('Ошибка сохранения: '+e.message)}}
  async function remove(){if(!state.originalPath)return newPage();if(!confirm(`Удалить «${state.title}»?`))return;await api('/api/editor/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:state.originalPath})});state.dirty=false;await refreshPages();state.pages.length?loadPage(state.pages[0].path):newPage()}
  function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
  function fileName(ext){return (state.path.split('/').pop()||Core.slugify(state.title)).replace(/\.md$/i,'')+'.'+ext}
  async function standalone(){let html=Core.renderBlocksHtml(state.blocks);const doc=new DOMParser().parseFromString(`<div id=x>${html}</div>`,'text/html');for(const img of doc.querySelectorAll('img')){const src=img.getAttribute('src');if(!src||/^data:/.test(src))continue;try{const r=await fetch(src);if(r.ok){const blob=await r.blob();img.src=await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(blob)})}}catch(_){}}html=doc.getElementById('x').innerHTML;download(fileName('html'),`<!doctype html><html lang=ru><meta charset=utf-8><style>${Core.previewCss}</style><article class=article>${html}</article></html>`,'text/html;charset=utf-8')}
  async function upload(file){if(!pendingUpload)return;try{const data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});const out=await api('/api/editor/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name,data})});pendingUpload.target[pendingUpload.key]=out.source;dirty();renderAll();toast('Изображение загружено')}catch(e){toast('Ошибка загрузки: '+e.message)}finally{pendingUpload=null}}

  refs.title.oninput=()=>{state.title=refs.title.value;if(state.newMode&&!state.pathTouched){state.path=`pages/${Core.slugify(state.title)}.md`;refs.path.value=state.path}const h=state.blocks.find(b=>b.type==='heading'&&b.level===1);if(h)h.html=state.title;dirty();renderAll()};refs.path.oninput=()=>{state.path=refs.path.value;state.pathTouched=true;dirty()};refs.group.onchange=()=>{if(refs.group.value==='__new__'){const n=prompt('Название нового раздела:','Новый раздел');if(n){state.group=n.trim();state.groups.push(state.group);fillGroups(state.group)}else fillGroups(state.group)}else state.group=refs.group.value;dirty()};refs.pageSearch.oninput=renderPageList;refs.picker.onchange=()=>{const f=refs.picker.files?.[0];if(f)upload(f)};
  $('newPage').onclick=newPage;$('duplicatePage').onclick=duplicate;$('savePage').onclick=save;$('deletePage').onclick=remove;$('downloadMd').onclick=()=>download(fileName('md'),currentContent(),'text/markdown;charset=utf-8');$('downloadHtml').onclick=standalone;$('openWiki').onclick=()=>window.open(state.currentHref||('/surwave-site/wiki/'+sourceToHref(state.path)),'_blank','noopener');document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}});window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});
  document.querySelectorAll('.mobile-tabs button').forEach(b=>b.onclick=()=>{const pv=b.dataset.view==='preview';refs.previewPanel.classList.toggle('mobile-visible',pv);refs.workspace.classList.toggle('mobile-hidden',pv)});
  (async()=>{try{await refreshPages();state.pages.length?await loadPage(state.pages[0].path):newPage()}catch(e){toast('Редактор не запустился: '+e.message);newPage()}})();
})();
